### ISSUE TITLE
Server Setup for the plugin?

### ISSUE THREAD

**Issue by mzeidhassan** [OpenNMT/Plugins#6]
Hi @panosk ,

There are 2 server solutions provided for OpenNMT. 
http://opennmt.net/OpenNMT/tools/servers/

I am using the second one (ZeroMQ), and in the plug in, I used the local IP address "tcp://192.168.1.166" of my home server which is accessible from remote computers, but the plugin doesn't connect to the server. 

By the way, I used "tcp://192.168.1.166" and "http://192.168.1.166", but nothing works and SDL throws this error message "the remote name could not be resolved: 'tcp'". I also tried "0.0.0.0", but in vain.
 
Here is an image of my local server with the ZeroMQ server running and the model is loaded. 

https://ibb.co/d7p8tk

Do you know what is the exact setup needed for the plug-in to work? Do you use the first option or ZeroMQ in your setup?

Thanks again for your help!

**Comment by panosk** [comment]
Hi @mzeidhassan ,

As advertised, the plugin works with the REST translation server so you should switch to that.

Please try to use OpenNMT's forum or the documentation in the website for instructions on how to setup and run the REST server, you will get more insight there.
